apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    path: helm-guestbook
    chart: helm-guestbook
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/asad-abdullah/helm-chart-demo.git'
    targetRevision: master
    ref: values
