apiVersion: v1
entries:
  demo-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-16T21:34:49.9598742+08:00"
    description: A Helm chart for Kubernetes
    digest: 1f571bbdcbe392674de39e9862d4b3d69f7931e01cc723992279a54f9c1ee94d
    name: demo-chart
    type: application
    urls:
    - demo-chart-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-16T21:34:49.9588568+08:00"
    description: A Helm chart for Kubernetes
    digest: fc0ec34a61091d9b4b53f2f8de8d4de5a5f6c3a9ef878bbd8f0fed418576b6cc
    name: demo-chart
    type: application
    urls:
    - demo-chart-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-16T21:34:49.9578575+08:00"
    description: A Helm chart for Kubernetes
    digest: 260eb53e73106b678dcb9c4107de783e1c9d2399f1e66a07b241017e1b89246e
    name: demo-chart
    type: application
    urls:
    - demo-chart-0.0.1.tgz
    version: 0.0.1
generated: "2023-01-16T21:34:49.9570196+08:00"
