{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-chart.fullname" . }}
  labels:
    {{- include "demo-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
{{- with .Values.configMap.config }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}