apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-chart.fullname" . }}
  labels:
    {{- include "demo-chart.labels" . | nindent 4 }}
{{- with .Values.config }}
data:
  {{- toYaml . | nindent 4 }}
{{- end }}
